"""update

Revision ID: 60f263991146
Revises: ca298ed4b1e5
Create Date: 2025-08-18 20:34:53.594261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f263991146'
down_revision = 'ca298ed4b1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clean_data', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('clean_data_url_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_clean_data_url'), ['url'], unique=True)
        batch_op.drop_column('child_id')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('predict_data', schema=None) as batch_op:
        batch_op.alter_column('child_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('log_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict_data', schema=None) as batch_op:
        batch_op.alter_column('log_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('parent_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('child_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('clean_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('child_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_clean_data_url'))
        batch_op.create_unique_constraint(batch_op.f('clean_data_url_key'), ['url'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
