"""update

Revision ID: 8f2a4bc529d3
Revises: f624264f3c00
Create Date: 2025-08-12 01:28:19.635167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2a4bc529d3'
down_revision = 'f624264f3c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict_data', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('predict_data_url_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict_data', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('predict_data_url_key'), ['url'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
