"""update

Revision ID: ca298ed4b1e5
Revises: 
Create Date: 2025-08-14 09:43:17.911953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca298ed4b1e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clean_data',
    sa.Column('clean_data_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('stopword_removed_tokens', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('link_gambar', sa.Text(), nullable=True),
    sa.Column('folder_gambar', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('clean_data_id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('predict_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=False),
    sa.Column('log_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('stopword_removed_tokens', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_classification')
    op.drop_table('predict_data')
    op.drop_table('clean_data')
    # ### end Alembic commands ###
